[package]
name = "day7"
version = "0.1.0"
edition = "2021"
default-run = "day7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"

[[bin]]
name = "alternate"
path = "src/alternate.rs"

